### PR TITLE
rename db to teamware_db

### PR DESCRIPTION
**Pull request by davidwilby**
I've put this in its own pull request so we can  attempt to do this safely.
Perhaps there should also be an identical PR against `master` so we can deploy this one change on it's own?

Open to discussion here.

### CODE REVIEW

**Comment by ianroberts** [comment]
I've added a "changelog" section to the Helm chart readme with instructions on how to handle this change for existing installations - our staging and production installations already have the required override in their respective values files so they will not be affected by the change to the published chart.

**Review by ianroberts — APPROVED** [review]
As per my standalone comment, this is technically a breaking change for existing installations, but I've already updated our production and staging configurations with the necessary overrides so the change won't break those.

**Comment by ianroberts** [comment]
Changelog is a good idea, but note that the helm chart is versioned independently of teamware itself - you can update the chart to change something about the way it deploys teamware without changing which version gets deployed.

**Comment by davidwilby** [comment]
So shall we just keep the actual name of our database the same, since it's set in `generate-docker-env.sh` or the helm charts?

**Comment by ianroberts** [comment]
> So shall we just keep the actual name of our database the same

You mean for the existing production deployments in Sheffield - yes, that's what I've done so far.  This PR will change the default name for new installs but I've set an override to set it back to the old default in our specific deployments.

**Pull request merged**
